action_id: trunk-upgrade-available
date: 2024-02-23 06:49:39
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1708670979
full_timestamp:
  nanos: 890045000
  seconds: 1708670979
trunk_version: 1.19.0
